### PR TITLE
Add ignoreTables flag

### PR DESCRIPTION
**Pull request by jamieaitken**
I have a scenario where I want to generate a mermaid diagram for the entire schema but exclude a couple of specific tables.

In order to achieve this, I've added a `ignoreTables` flag consisting of a slice of strings. The exact name of the tables can be given or you can pass a regex pattern.

### CODE REVIEW

**Comment by jamieaitken** [comment]
@KarnerTh could you have a look at this please 🙏

**Comment by KarnerTh** [comment]
Thank you very much! Will try to review it this weekend.

Would fix #56

**Comment by KarnerTh** [comment]
Great work @jamieaitken 🙌🏼 
Just added some minor changes

**Comment by KarnerTh** [comment]
Changes are available in version [0.11.0](https://github.com/KarnerTh/mermerd/releases/tag/v0.11.0)

**Pull request merged**
