### PR TITLE
Sort columns

### PR DESCRIPTION
**Pull request by aslakhellesoy**
This is a fix for #40.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
I just realised that constraints need to be sorted as well. So I'm wondering if it would be better to move all the sorting logic (tables, columns, constraints) to `diagram.go` instead. If you agree with this approach I can update this PR.

**Comment by aslakhellesoy** [comment]
Hi @KarnerTh - any thoughts or feedback about this?

**Comment by KarnerTh** [comment]
Hi @aslakhellesoy! 
Thank you very much for the PR 🙌🏼 

I will happily merge back your changes. I would keep the sorting logic in the analyser, because the diagram.go has the only responsibility to create the diagram and in my opinion sorting is part of the analysing process.

**Comment by aslakhellesoy** [comment]
Thanks for merging this @KarnerTh! 🤝

**Pull request merged**
